sudo: require
services:
  -docker


before_install:
  - docker build -t dorlan25/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true dorlan25/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-133168527482"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  access_key_id:
    secure: "$AWS_SECRET_KEY"


     Docker-env.zqf28edbpi.us-east-2.elasticbeanstalk.com